url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Eunbi Kim" # the name of your site, e.g. ACME Corp.
description: "Graduate Student in Applied Data Science at Syracuse University"
